force-app/main/default/objects/Record_Criteria__c/Record_Criteria__c.object-meta.xml
<CustomObject>
    <label>Record Criteria</label>
    <nameField>
        <label>Record Criteria  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Criteria__c/fields/Field_1__c.field-meta.xml
<CustomField>
    <fullName>Field_1__c</fullName>
    <description>This is the field of the Sobject record that is used to compare against</description>
    <label>Field 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Field_2__c.field-meta.xml
<CustomField>
    <fullName>Field_2__c</fullName>
    <description>This is the field of the Sobject record that is used to compare against</description>
    <label>Field 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Field_3__c.field-meta.xml
<CustomField>
    <fullName>Field_3__c</fullName>
    <description>This is the field of the Sobject record that is used to compare against</description>
    <label>Field 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Field_4__c.field-meta.xml
<CustomField>
    <fullName>Field_4__c</fullName>
    <description>This is the field of the Sobject record that is used to compare against</description>
    <label>Field 4</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Field_5__c.field-meta.xml
<CustomField>
    <fullName>Field_5__c</fullName>
    <description>This is the field of the Sobject record that is used to compare against</description>
    <label>Field 5</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Operation_1__c.field-meta.xml
<CustomField>
    <fullName>Operation_1__c</fullName>
    <description>This is the Operation that will take place. For example 

Field 1 Operation Value 1</description>
    <label>Operation 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>=&lt;</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Operation_2__c.field-meta.xml
<CustomField>
    <fullName>Operation_2__c</fullName>
    <description>This is the Operation that will take place. For example

        Field 2 Operation Value 2</description>
    <label>Operation 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>=&lt;</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Operation_3__c.field-meta.xml
<CustomField>
    <fullName>Operation_3__c</fullName>
    <description>This is the Operation that will take place. For example

        Field 3 Operation Value 3</description>
    <label>Operation 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>=&lt;</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Operation_4__c.field-meta.xml
<CustomField>
    <fullName>Operation_4__c</fullName>
    <description>This is the Operation that will take place. For example

        Field 4 Operation Value 4</description>
    <label>Operation 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>=&lt;</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Operation_5__c.field-meta.xml
<CustomField>
    <fullName>Operation_5__c</fullName>
    <description>This is the Operation that will take place. For example

        Field 5 Operation Value 5</description>
    <label>Operation 5</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>=&lt;</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Overall_Operation__c.field-meta.xml
<CustomField>
    <fullName>Overall_Operation__c</fullName>
    <label>Overall Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>AND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Value_1__c.field-meta.xml
<CustomField>
    <fullName>Value_1__c</fullName>
    <description>This will check with the operation type in Value 1</description>
    <label>Value 1</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Value_2__c.field-meta.xml
<CustomField>
    <fullName>Value_2__c</fullName>
    <description>This will check with the operation type in Value 2</description>
    <label>Value 2</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Value_3__c.field-meta.xml
<CustomField>
    <fullName>Value_3__c</fullName>
    <description>This will check with the operation type in Value 3</description>
    <label>Value 3</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Value_4__c.field-meta.xml
<CustomField>
    <fullName>Value_4__c</fullName>
    <description>This will check with the operation type in Value 4</description>
    <label>Value 4</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Value_5__c.field-meta.xml
<CustomField>
    <fullName>Value_5__c</fullName>
    <description>This will check with the operation type in Value 5</description>
    <label>Value 5</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RecordCriteriaEvaluator_Test.cls
@isTest
public with sharing class RecordCriteriaEvaluator_Test {
    @isTest
    public static void evaluationCriteraShouldReturnCorrectValueForAllCases(){
        RecordCriteriaEvaluator evaluation = new RecordCriteriaEvaluator();
        Account acc = new Account(
            Name='Test Account 1',
            AnnualRevenue=1000,
            Rating='Hot'
        );
        for(Record_Criteria__c recordCriteria:makeSingleEvaluationRecordCriterias()){
            evaluation.setEvaluationRecord(recordCriteria).setSObject(acc);
            Assert.isTrue(evaluation.evaluationCritera('Field_1__c','Operation_1__c','Value_1__c'),'The evaluation should pass for'+ recordCriteria.Name);
        }
    }
    @isTest
    public static void evaluationShouldReturnCorrectOverallValue(){
        Map<String,Record_Criteria__c> evalutionRecordsWithMultipleCriteriaByScenarioNames =makeMultipleEvalutionRecordCriteriasByName();
        RecordCriteriaEvaluator evaluation = new RecordCriteriaEvaluator();
        Account acc = new Account(
            Name='Test Account 1',
            AnnualRevenue=1000,
            Rating='Hot'
        );
        evaluation.setSObject(acc);
        Assert.isFalse((evaluation.setEvaluationRecord(evalutionRecordsWithMultipleCriteriaByScenarioNames.get('Testing for 5 false criteria on AND Type'))).evaluate(),'Testing for 5 false criteria on AND Type should return false');
        Assert.isTrue((evaluation.setEvaluationRecord(evalutionRecordsWithMultipleCriteriaByScenarioNames.get('Testing for 5 true criteria on AND Type'))).evaluate(),'Testing for 5 true criteria on AND Type should return true');
        Assert.isFalse((evaluation.setEvaluationRecord(evalutionRecordsWithMultipleCriteriaByScenarioNames.get('Testing for 5 false criteria on OR Type'))).evaluate(),'Testing for 5 false criteria on OR Type should return false');
        Assert.isTrue((evaluation.setEvaluationRecord(evalutionRecordsWithMultipleCriteriaByScenarioNames.get('Testing for 5 true criteria on OR Type'))).evaluate(),'Testing for 5 true criteria on OR Type should return true');
        Assert.isFalse((evaluation.setEvaluationRecord(evalutionRecordsWithMultipleCriteriaByScenarioNames.get('Testing for 1 true criteria in middle on AND Type'))).evaluate(),'Testing for 1 true criteria in middle on AND Type should return false');
        Assert.isTrue((evaluation.setEvaluationRecord(evalutionRecordsWithMultipleCriteriaByScenarioNames.get('Testing for 1 true criteria in middle on OR Type'))).evaluate(),'Testing for 1 true criteria in middle on OR Type should return true');

    }
    public static List<Record_Criteria__c> makeSingleEvaluationRecordCriterias(){
        return new List<Record_Criteria__c>{
            new Record_Criteria__c(
                Name='Criteria 1',
                Field_1__c='AnnualRevenue',
                Operation_1__c='=',
                Value_1__c='1000'
            ),
            new Record_Criteria__c(
                Name='Criteria 2',
                Field_1__c='AnnualRevenue',
                Operation_1__c='>',
                Value_1__c='1'
            ),
            new Record_Criteria__c(
                Name='Criteria 3',
                Field_1__c='AnnualRevenue',
                Operation_1__c='<',
                Value_1__c='10000'
            ),
            new Record_Criteria__c(
                Name='Criteria 4',
                Field_1__c='AnnualRevenue',
                Operation_1__c='>=',
                Value_1__c='1000'
            ),
            new Record_Criteria__c(
                Name='Criteria 5',
                Field_1__c='AnnualRevenue',
                Operation_1__c='<=',
                Value_1__c='1000'
            ),
            new Record_Criteria__c(
                Name='Criteria 6',
                Field_1__c='Rating',
                Operation_1__c='Contains',
                Value_1__c='Hot'
            ),
            new Record_Criteria__c(
                Name='Criteria 7',
                Field_1__c='Rating',
                Operation_1__c='Contains Right ;',
                Value_1__c='Hot;Cold;Warm'
            )
        };
    }
    public static Map<String,Record_Criteria__c> makeMultipleEvalutionRecordCriteriasByName(){
        return new Map<String,Record_Criteria__c>{
            'Testing for 5 false criteria on AND Type' =>
            new Record_Criteria__c(
                Name='Testing for 5 false criteria on AND Type',
                Field_1__c='AnnualRevenue',
                Operation_1__c='=',
                Value_1__c='1',
                Field_2__c='AnnualRevenue',
                Operation_2__c='=',
                Value_2__c='1',
                Field_3__c='AnnualRevenue',
                Operation_3__c='=',
                Value_3__c='1',
                Field_4__c='AnnualRevenue',
                Operation_4__c='=',
                Value_4__c='1',
                Field_5__c='AnnualRevenue',
                Operation_5__c='=',
                Value_5__c='1',
                Number_of_Criteria__c=5,
                Overall_Operation__c='AND'
            ),
            'Testing for 5 true criteria on AND Type' =>
            new Record_Criteria__c(
                Name='Testing for 5 true criteria on AND Type',
                Field_1__c='AnnualRevenue',
                Operation_1__c='=',
                Value_1__c='1000',
                Field_2__c='AnnualRevenue',
                Operation_2__c='=',
                Value_2__c='1000',
                Field_3__c='AnnualRevenue',
                Operation_3__c='=',
                Value_3__c='1000',
                Field_4__c='AnnualRevenue',
                Operation_4__c='=',
                Value_4__c='1000',
                Field_5__c='AnnualRevenue',
                Operation_5__c='=',
                Value_5__c='1000',
                Number_of_Criteria__c=5,
                Overall_Operation__c='AND'
            ),
            'Testing for 5 false criteria on OR Type' =>
            new Record_Criteria__c(
                Name='Testing for 5 false criteria on OR Type',
                Field_1__c='AnnualRevenue',
                Operation_1__c='=',
                Value_1__c='1',
                Field_2__c='AnnualRevenue',
                Operation_2__c='=',
                Value_2__c='1',
                Field_3__c='AnnualRevenue',
                Operation_3__c='=',
                Value_3__c='1',
                Field_4__c='AnnualRevenue',
                Operation_4__c='=',
                Value_4__c='1',
                Field_5__c='AnnualRevenue',
                Operation_5__c='=',
                Value_5__c='1',
                Number_of_Criteria__c=5,
                Overall_Operation__c='OR'
            ),
            'Testing for 5 true criteria on OR Type' =>
            new Record_Criteria__c(
                Name='Testing for 5 true criteria on OR Type',
                Field_1__c='AnnualRevenue',
                Operation_1__c='=',
                Value_1__c='1000',
                Field_2__c='AnnualRevenue',
                Operation_2__c='=',
                Value_2__c='1000',
                Field_3__c='AnnualRevenue',
                Operation_3__c='=',
                Value_3__c='1000',
                Field_4__c='AnnualRevenue',
                Operation_4__c='=',
                Value_4__c='1000',
                Field_5__c='AnnualRevenue',
                Operation_5__c='=',
                Value_5__c='1000',
                Number_of_Criteria__c=5,
                Overall_Operation__c='OR'
            ),
            'Testing for 1 true criteria in middle on AND Type' =>
            new Record_Criteria__c(
                Name='Testing for 1 true criteria in middle on AND Type',
                Field_1__c='AnnualRevenue',
                Operation_1__c='=',
                Value_1__c='1',
                Field_2__c='AnnualRevenue',
                Operation_2__c='=',
                Value_2__c='1',
                Field_3__c='AnnualRevenue',
                Operation_3__c='=',
                Value_3__c='1',
                Field_4__c='AnnualRevenue',
                Operation_4__c='=',
                Value_4__c='1000',
                Field_5__c='AnnualRevenue',
                Operation_5__c='=',
                Value_5__c='1',
                Number_of_Criteria__c=5,
                Overall_Operation__c='AND'
            ),
            'Testing for 1 true criteria in middle on OR Type' =>
            new Record_Criteria__c(
                Name='Testing for 1 true criteria in middle on OR Type',
                Field_1__c='AnnualRevenue',
                Operation_1__c='=',
                Value_1__c='1',
                Field_2__c='AnnualRevenue',
                Operation_2__c='=',
                Value_2__c='1',
                Field_3__c='AnnualRevenue',
                Operation_3__c='=',
                Value_3__c='1',
                Field_4__c='AnnualRevenue',
                Operation_4__c='=',
                Value_4__c='1000',
                Field_5__c='AnnualRevenue',
                Operation_5__c='=',
                Value_5__c='1',
                Number_of_Criteria__c=5,
                Overall_Operation__c='OR'
            )
        };

    }
}